defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:current
version: 2.1
workflows:
  ci-cd:
    jobs:
      - test:
          context: globalenv
      - publish:
          context: globalenv
          requires:
            - test
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i ; npm i -ws
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
      - run:
          name: Check code syntax
          command: npm run lint -- --plugin log
      - run:
          name: Test
          command: npm t
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set NPM tokens
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install published
          command: npm i -g published
      - run:
          name: Publish to NPM
          command: ./scripts/foreach.sh published
